CREATE TABLE IF NOT EXISTS USER (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(255) NOT NULL,
    order_id INT,
    FOREIGN KEY (order_id) REFERENCES ORDER(id)
);

CREATE TABLE IF NOT EXISTS ORDER (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_details VARCHAR(255),
);
